# Generated by Django 5.2.6 on 2025-09-16 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='accounts.board')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFFFFF', max_length=16, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.column')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tasks', to='accounts.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='accounts.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['owner'], name='accounts_bo_owner_i_518b15_idx'),
        ),
        migrations.AddIndex(
            model_name='boardmember',
            index=models.Index(fields=['board', 'user'], name='accounts_bo_board_i_7460cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['board', 'order'], name='accounts_co_board_i_fc1986_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['board', 'name'], name='accounts_ta_board_i_41122f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('board', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'order'], name='accounts_ta_column__f26395_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['task', 'tag'], name='accounts_ta_task_id_4cb8d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('task', 'tag')},
        ),
    ]
